// app/layout.js
import Layout from "@/layout/Layout";
import "./globals.css";
import localFont from "next/font/local";
import NextAuthProvider from "@/providers/NextAuthProvider";

const cabin = localFont({
  src: [
    {
      path: "../../public/fonts/Cabin-Bold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-cabin",
});

export const metadata = {
  title: "Sheltehub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cabin.variable}`} suppressHydrationWarning>
      <body className="font-sans min-h-screen flex flex-col">
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
      </body>
    </html>
  );
}